//-----------------------------------------------------------------------
// <copyright file="Example.cs" company="Archimed">
//     Company copyright tag.
// </copyright>
// <auto-generated/>
//-----------------------------------------------------------------------
namespace Mashup.Tests.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;
    using System.Threading.Tasks;

    [DataContract]
    public class Employee
    {

        [DataMember(Name = "firstName")]
        public string FirstName { get; set; }

        [DataMember(Name = "lastName")]
        public string LastName { get; set; }
    }

    [DataContract]
    public class Example
    {

        [DataMember(Name = "employee")]
        public Employee Employee { get; set; }
    }
}
