//-----------------------------------------------------------------------
// <copyright file="DeezerArtist.cs" company="Archimed">
//     Company copyright tag.
// </copyright>
// <auto-generated/>
//-----------------------------------------------------------------------
namespace Mashup.Provider.Service.Deezer.Model.Artist
{
    using System.Runtime.Serialization;

    [DataContract]
    public class DeezerArtist
    {
        [DataMember(Name = "id")]
        public int Id { get; set; }

        [DataMember(Name = "name")]
        public string Name { get; set; }

        [DataMember(Name = "link")]
        public string Link { get; set; }

        [DataMember(Name = "share")]
        public string Share { get; set; }

        [DataMember(Name = "picture")]
        public string Picture { get; set; }

        [DataMember(Name = "picture_small")]
        public string PictureSmall { get; set; }

        [DataMember(Name = "picture_medium")]
        public string PictureMedium { get; set; }

        [DataMember(Name = "picture_big")]
        public string PictureBig { get; set; }

        [DataMember(Name = "nb_album")]
        public int NBAlbum { get; set; }

        [DataMember(Name = "nb_fan")]
        public int NBFan { get; set; }

        [DataMember(Name = "radio")]
        public bool Radio { get; set; }

        [DataMember(Name = "tracklist")]
        public string Tracklist { get; set; }

        [DataMember(Name = "type")]
        public string DeezerArtistType { get; set; }
    }
}