//-----------------------------------------------------------------------
// <copyright file="LastFMArtist.cs" company="Archimed">
//     Company copyright tag.
// </copyright>
// <auto-generated/>
//-----------------------------------------------------------------------
namespace Mashup.Provider.Service.LastFM.Model.Artist
{
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public class Image
    {

        [DataMember(Name = "#text")]
        public string Text { get; set; }

        [DataMember(Name = "size")]
        public string Size { get; set; }
    }

    [DataContract]
    public class Stats
    {

        [DataMember(Name = "listeners")]
        public string Listeners { get; set; }

        [DataMember(Name = "playcount")]
        public string Playcount { get; set; }
    }

    [DataContract]
    public class SimilarArtist
    {

        [DataMember(Name = "name")]
        public string Name { get; set; }

        [DataMember(Name = "url")]
        public string Url { get; set; }

        [DataMember(Name = "image")]
        public IList<Image> Image { get; set; }
    }

    [DataContract]
    public class Similar
    {

        [DataMember(Name = "artist")]
        public IList<SimilarArtist> Artist { get; set; }
    }

    [DataContract]
    public class Tag
    {

        [DataMember(Name = "name")]
        public string Name { get; set; }

        [DataMember(Name = "url")]
        public string Url { get; set; }
    }

    [DataContract]
    public class Tags
    {

        [DataMember(Name = "tag")]
        public IList<Tag> Tag { get; set; }
    }

    [DataContract]
    public class Link
    {

        [DataMember(Name = "#text")]
        public string Text { get; set; }

        [DataMember(Name = "rel")]
        public string Rel { get; set; }

        [DataMember(Name = "href")]
        public string Href { get; set; }
    }

    [DataContract]
    public class Links
    {

        [DataMember(Name = "link")]
        public Link Link { get; set; }
    }

    [DataContract]
    public class Bio
    {

        [DataMember(Name = "links")]
        public Links Links { get; set; }

        [DataMember(Name = "published")]
        public string Published { get; set; }

        [DataMember(Name = "summary")]
        public string Summary { get; set; }

        [DataMember(Name = "content")]
        public string Content { get; set; }
    }

    [DataContract]
    public class Artist
    {

        [DataMember(Name = "name")]
        public string Name { get; set; }

        [DataMember(Name = "mbid")]
        public string Mbid { get; set; }

        [DataMember(Name = "url")]
        public string Url { get; set; }

        [DataMember(Name = "image")]
        public IList<Image> Image { get; set; }

        [DataMember(Name = "streamable")]
        public string Streamable { get; set; }

        [DataMember(Name = "ontour")]
        public string Ontour { get; set; }

        [DataMember(Name = "stats")]
        public Stats Stats { get; set; }

        [DataMember(Name = "similar")]
        public Similar Similar { get; set; }

        [DataMember(Name = "tags")]
        public Tags Tags { get; set; }

        [DataMember(Name = "bio")]
        public Bio Bio { get; set; }
    }

    [DataContract]
    public class LastFMArtist
    {

        [DataMember(Name = "artist")]
        public Artist Artist { get; set; }
    }

}